version: '1.0'
services:
    web_go_book_management:
        container_name: "web_go_book_management"
        build: .
        volumes:
            - "./go/:/go"
            - "./book/:/book"
        ports:
            - "8080:8080"
        tty: true # コンテナの永続化
        depends_on:
            - mysql_go_book_management
        #privileged: true
    mysql_go_book_management:
        container_name: mysql_go_book_management
        platform: linux/x86_64 # M1チップ対応のため追記
        image: mysql:8
        volumes:
            - ./mysql:/var/lib/mysql
            - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=test_root_986
            - MYSQL_DATABASE=test_db_964
            - MYSQL_USER=test_user_985
            - MYSQL_PASSWORD=test_password_524
        ports:
            - "4307:3306"