version: '1.0'
services:
    mysql_go_book_management:
        container_name: mysql_go_book_management
        hostname: mysql
        image: mysql:8.3
        platform: linux/amd64
        volumes:
            - ./mysql:/var/lib/mysql
            - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
        environment:
            - MYSQL_ROOT_PASSWORD=password123
            - MYSQL_DATABASE=sample
        ports:
            - "3306:3306"
    web_go_book_management:
        container_name: "web_go_book_management"
        build: .
        volumes:
            - "./go/:/go"
            - "./book/:/book"
        ports:
            - "5173:5173"
        tty: true # コンテナの永続化
        depends_on:
            - mysql_go_book_management
        #privileged: true


